name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: macOS-10.15
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        set -o pipefail && xcodebuild -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG|xcpretty
        
